os:
  - linux
  - osx

compiler:
  - clang
language: c++
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - perl
    - gcc-4.8
    - g++-4.8
    - python-dev
    - python-numpy
    - libxml2-dev
    - libboost-all-dev
    - cmake


env:
  global:  
#             FTP_USER 
    - secure: "C0mR7nU9wTGtrGtRdgfbBJQehaTD+coItsg9iQMQzHT3tUGJ3VJ0wZ6qEp4waNBcCNSk5jIpoqkJIZXRXny1G+iNHA2o115Zg7D0Ekk04zaf3V4J4TGAEgyWDgncPvfnbewjOOorCi0XhPNgJMJQ052HDtqA6ndWUr4eiOGt9fAdJ9srhwO512vu+rIFBJLuLENL0D/x0u5/vzBBW+9wHzQGjjfYM8/EQrpCTbtd59oP3GF6csH/t1KPrR5XiyhLzsU8dv7Fi7ch+tDwiNTw9/XqZhGixBwC+lDiuqemHUObqmoGIqgdAGClPZydLZebg8Ld0sd2GJokocStTI2oz7hzSPN/LmQwkceWDyI+rr56sD57gzh6fuYww5bRAAYiDXJSJx6bqtoZZA/tPAMOO/6gT8MaFImXOygiB4R4Fzh89pBibe9XupXvooKhGucPJtLMB5w4+pJKonAqcXZbsUp2uuRq9amr2N26CKd2BKPLwOK72jzHh9Dcwqj7MRcjvGAa73c9rJjfYCIlwYxTlxfeXrJOHZIG6k5upkZdQD/f6U+REiO9crz9kV+gQAk5vGd3xBD/FnPm2OCMuuVPioyngQLdZ+NbylOPF0pIQQn2HVx3T1QcxBkQGKJP81gf7vETjKBQFOmHnW0BWRyliM7+1EFUNbfVAzjNnykui0w="
#             FTP_PASSWORD
    - secure: "sVq5/odFNeKbOvXgPvXkUEuIfSA58DjESOZBj/gELPd+TL4M+eK8TuSsQOuIyiKNCvxMf+QRPnPqfcWMUpl2ns2pvR1JJcx7uUzfOPbQtWiUuiy1WZw/Xk+xEyspr22TfMJK6atV5PPxJWv54d2c16S5Pp+oUHpvURW7Q0V0kan7O6ndL+KFwTVFVJ3Exhn6KVdbr2MpbRkBmJIM9v+jF59T5rfxTgSrp5spKGJeRS/BsDl7Su13f+fMnnK7zOtN4TLwo/SjPwHfLEMhPrWSSH/Qlr8mzsuloiP4VQdnmGHOldBVQ5LaABZspkVDeusGPVeK2RWh2JT1Pt1w/bAPckLFzVOyQvuqhQ7r0OtulcwZcWhfziVzoJgGotvkKUnoPBM+tUCUh59iGTpWyDW09hQaozxrc2V/6PkuTZsYS2dZfUjiiF0lG/aeL0JJaNiiySUbVFgmU9GxT2D3i96cmKIJNxGTrio2wD8QV+cvvL49UOMTy1WiAkdwcCB0i22UKUrkv+Hqrikher6Sy4qUK5IikxrkBHLeVQHvY/IKbd8T72pN4ck+fpLDt2acvExEZUjhEPw+WYZQcxKxfq/FscuuQXsurVHJxQSJia7Ssqp923qbZf4Ex2bQf8fjsC7J6/pDQrHWjQ0AozZBLwR+ZYRyyRBCbrfVQwd8ibpQHIQ="


notifications:
  slack:
    rooms:
      - secure: Rxjp4bNLl/kx9dbQxpXtHi2KEl7M25/gJcG874IlF40B9tnPwRmGm+w8m3smQW7gRNLyZ6VfoBcmuGet+GMBTCCa44dCcm9qkx+OZJkOBv/C5TLEO4dBtAMFDhRRmpr2LhZfxvbC0R0CRP3wzGIea4RWFJBcvF/oAtGxYSfISpEE745DDY/W9yNRk3AchFDvb9T3f6ip3JDJnamdBh5xMUD1Ou6HiTUjXm4qrwwG89Lf9MrzmN3LOuP/+wE/w+wz4MeEYuPWMfQIYGdI0Bhz7zglmRpBPX4F6FSN9LyBrTORZz09erXLwcz7kyP+LfA3cXrvoMSD4eR8mSyRxV20o7p5+phHNdYkpohmoOwOPO7cT/yfSSjQIzCN4NYeIxTTXed4AyAfDFCVrB8o5sqs2QC1O7MuNOgKw1DDvUMNRLd+8x41xpdr0dZC1OxgJ0glURaHq1e7C2GqjzKgd0wm1bYhnOWWLMwe4S9mrxo8/bKG6JQ0TchXkr5PHo02QT+HTiDysDgsa+etyM4zIMbNpp3aYQsNMxu3IOgzINUgcnoVreyXlht1QGEu8I6WIWNWYnBmdjx+aK7V2dKeEx5LLqJ/RO5+CWaXyYIdg7EYQn/WIx9Z5ifCs4s8m7ZqKYd6D+1KpfrrhMtnZ/uTJ/HVHkLwyW7DX/caRn7kpnQU5Xc=
    template:
      - "NFsim build: %{result} in %{duration}"
      - "Build: <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) Author: %{author}"   
      - "To download the NFsim executable, "
      - "Goto: https://rawgit.com/RuleWorld/nfsim/master/.NFsim_Beta.html"
      - "To package NFsim, please make a small modification to BioNetGen:"
      - "Goto: https://github.com/RuleWorld/bionetgen"
      - "Build details:  %{build_url} "


before_install:
- source osx_install.sh

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script: 
  - mkdir -p build; mkdir -p dist; cd build; cmake ..; make; cp NFsim ../dist; cp NFsim ../dist/NFsim-$TRAVIS_OS_NAME ;cd ..; 
  - cd validate;tar xfj bionetgen-2.2.6.tar.bz2
  - python validate.py
  - cd ..
  - source .curl_ftp.sh
# Putting the curl statement here, will ensure that an executable will be uploaded, even though the test suite may have
# completed with one or more failures.
  
after_success:
#  - source .curl_ftp.sh
