os:
  - linux
language: c++
sudo: false
addons:
  apt:
    packages:
    - python-dev
    - python-numpy
    - libxml2-dev
    - libxmlrpc-core-c3-dev
    - libxmlrpc-c++8-dev
compiler:
  - g++
notifications:
  slack: faederlab:bJ2pu0hViE70sbIKASmmT74r
script: mkdir build; cd build; cmake ..; make; cd ..;cd validate;tar xfj bionetgen-2.2.6.tar.bz2;python validate.py
