os:
  - linux
language: c++
compiler:
  - gcc
  - clang
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports

    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - python-dev
    - python-numpy
    - libxml2-dev
    - libxmlrpc-core-c3-dev
    - libxmlrpc-c++8-dev
    - libboost-all-dev
    - cmake
    - ninja-build
compiler:
  - g++
notifications:
  slack: faederlab:bJ2pu0hViE70sbIKASmmT74r

before_script:
    - cd dep
    - tar xfz xmlrpc-c-1.33.18.tgz
    - cd xmlrpc-c-1.33.18
    - ./configure --prefix=$PWD/xmlrpc; make; make install
    - cd xmlrpc
    - mv include ../../..
    - mv lib ../../..
    - cd ../../..
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script: mkdir build; cd build; cmake -G "Ninja" ..; ninja; cd ..;cd validate;tar xfj bionetgen-2.2.6.tar.bz2;python validate.py
