os:
- linux
- osx
language: c++
sudo: false
addons:
  apt:
    packages:
    - python-dev
    - python-numpy
    - libxml2-dev
compiler:
- g++
notifications:
  slack: faederlab:bJ2pu0hViE70sbIKASmmT74r
before_install:
- source osx_install.sh
script: mkdir -p build; mkdir -p dist; cd build; cmake ..; make; cp NFsim ../dist; cd ..; cd validate;tar xfj bionetgen-2.2.6.tar.bz2;python validate.py; cd ..

