os:
  - linux
  - osx

compiler:
  - clang
language: c++
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - perl
    - gcc-4.8
    - g++-4.8
    - python-dev
    - python-numpy
    - libxml2-dev
    - libboost-all-dev
    - cmake


env:
  global:  
#             FTP_USER 
    - secure: "Plaw2ZaWrlAJENZx+93ZUctF2cemslx2a0xxNLvxZ0smIL3yD0htwoEVDqCZUY5kLj8F1GYTV9lA1+6trUgL2rsJ0RxhutVKEGOVLl1Bqvzr9Pu9U4zAzrwLBjgeIyvjASzigMfT15vRteyVnTFOsFWh3wnzTzU+yUDt+Kt4wibNNnWZjzJwP37NDgneYBNFXchL+cHXFsXYa1hWTgbCS8U6+TQtCC9bncHRY1j+yPpxmZbiulF8Ha+WOxHz1RR1xjOUxhn87wxjctCvXucoia3OB62i2kt3brG9R6+dDS9b0LaOox6T+HJrHVuMg/rdlESyIU8t0/sN1CPeCK5S6YIvTM7Mpiefm288rVlLz3cYr43qWydJLrDb3p6ksvaSrPVKNDVy9772gDSIPi5E6V14S49+uS/MfBHGJB6C6CdhezQRuANI0oUcQCZrs+dKeYAcbRsfbjO4frsPeqFlch9iHxnDIYyMo5ji3LyJXHopOaysMWGb6n2VVZXa9y+Kkga+mUv1y04oO7c7KpCR24SHo7ebCfGCBjLpT5aN8FC5agvCCIEgmuGdO82PwdQ8oS/TO5krzcQsnYK0NtFrO98Js1ti3zhy3TjQfaas/vmMbcVUOP9Gyayu0vhcDcOeOG2i1VWfR+7lT502yqURU6T7l468Ygmj2+bwayZUouk="
#             FTP_PASSWORD
    - secure: "KbUYhTv1X9/HviHaIhBmrM2DpttN3tcM7PlPV3HJB4smk7rV4VvUDvqyiic2PvGyQ/M4Pidp2OuaU2WQlntSUlb2jrUZzL4kUYb461GZo46il5AWsILW3Rxa6ieorLXpjaMlW4iafXYEQIhD5mehG26V9vsrHvqLBULINs47cMXxjZFPbgtShBgSeC5tHCij8dUuPCKRQjGEMushzOZVIvfV98gBC+0OkqaAEgeLUerOlwnqfxL6snzONGOEvOpevP+wjV04NTM/gEyBwP/ZE3ivZjFdzMkYZoddfyyRUQTpVbqoZ2e/RBbY9UX0fUF6NoNvCB8f+toNypl0Qr7GUvsYi91Yke51wbps9OOLbOKoRIt9m5lHCzjRr/S2CqhbdqlS8d0QtTycoM+vb519/IbRff//tIeVynZBUsxDuZZbpXGoCl5NjcKCkX1plX1byJ+O7YEJc2RPNx1Db7jce5gxvVX5n0Kgspt/+8+k5c1tQt+ktDQLxLKvnUSA0ptTzEdhqlVettT4L7+3roLLTiEwHGDJVefIHHOvQ+jiB6f26UFLPvVLpyCONP4NDKBIZk+Fk8qPhrnB0LrggiAid2xgeT8nED2aG/0GFyaykX5IcjsSZiQBWj35DP2cP0ExeYbA9ohO26bMvB5cNLHvkLp2w+0yOP05RXM6I7nt0cw="


notifications:
  slack:
    rooms:
      - secure: Rxjp4bNLl/kx9dbQxpXtHi2KEl7M25/gJcG874IlF40B9tnPwRmGm+w8m3smQW7gRNLyZ6VfoBcmuGet+GMBTCCa44dCcm9qkx+OZJkOBv/C5TLEO4dBtAMFDhRRmpr2LhZfxvbC0R0CRP3wzGIea4RWFJBcvF/oAtGxYSfISpEE745DDY/W9yNRk3AchFDvb9T3f6ip3JDJnamdBh5xMUD1Ou6HiTUjXm4qrwwG89Lf9MrzmN3LOuP/+wE/w+wz4MeEYuPWMfQIYGdI0Bhz7zglmRpBPX4F6FSN9LyBrTORZz09erXLwcz7kyP+LfA3cXrvoMSD4eR8mSyRxV20o7p5+phHNdYkpohmoOwOPO7cT/yfSSjQIzCN4NYeIxTTXed4AyAfDFCVrB8o5sqs2QC1O7MuNOgKw1DDvUMNRLd+8x41xpdr0dZC1OxgJ0glURaHq1e7C2GqjzKgd0wm1bYhnOWWLMwe4S9mrxo8/bKG6JQ0TchXkr5PHo02QT+HTiDysDgsa+etyM4zIMbNpp3aYQsNMxu3IOgzINUgcnoVreyXlht1QGEu8I6WIWNWYnBmdjx+aK7V2dKeEx5LLqJ/RO5+CWaXyYIdg7EYQn/WIx9Z5ifCs4s8m7ZqKYd6D+1KpfrrhMtnZ/uTJ/HVHkLwyW7DX/caRn7kpnQU5Xc=
    template:
      - "NFsim build: %{result} in %{duration}"
      - "Build: <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) Author: %{author}"   
      - "To download the NFsim executable, "
      - "Goto: https://rawgit.com/RuleWorld/nfsim/master/.NFsim_Beta.html"
      - "To package NFsim, please make a small modification to BioNetGen:"
      - "Goto: https://github.com/RuleWorld/bionetgen"
      - "Build details:  %{build_url} "


before_install:
- source osx_install.sh

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script: 
  - mkdir -p build; mkdir -p dist; cd build; cmake ..; make; cp NFsim ../dist; cp NFsim ../dist/NFsim-$TRAVIS_OS_NAME ;cd ..; 
  - cd validate;tar xfj bionetgen-2.2.6.tar.bz2
  - python validate.py
  - cd ..
  
after_success:
#  - perl .make_tar.pl  --platform $TRAVIS_OS_NAME
  - source .curl_ftp.sh
