os:
  - linux
language: c++
sudo: false
addons:
  apt:
    packages:
    - python-dev
    - python-numpy
    - libxml2-dev
compiler:
  - g++
notifications:
  slack: faederlab:bJ2pu0hViE70sbIKASmmT74r
#cd validate;tar xfj bionetgen-2.2.6.tar.bz2;python validate.py
script: mkdir -p build; mkdir -p bin; cd build; cmake ..; make; cp NFsim ../bin; cd ..;
deploy:
  provider: s3
  access_key_id: "AKIAJEOXCCXGUFNFW6MA"
  secret_access_key: "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"
  bucket: "nfsim"
  skip_cleanup: true
  local_dir: bin
  on:
    branch: release
