os:
  - linux
  - osx

compiler:
  - clang
language: c++
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - perl
    - gcc-4.8
    - g++-4.8
    - python-dev
    - python-numpy
    - libxml2-dev
    - libboost-all-dev
    - cmake


env:
  global:  
#             FTP_USER_4 
    - secure: "djQnGCmDLIUCanzq9z9rAyBSjo+eV16AWoSBlaj/oJMMrxC6YMb7drImFUvKI9Ygpc0+hznJIOzgj/pfsGzIDl5s+UUyDGdzvzkg+S3YXRpBLMsjoGmIAsIE7nVkoXYDkF1nwV4RNRRbfspqhbyZPd+ayonsgbMrDL1SYz7LDZmXBTEY1foAchPzDy+qcxnhXmFb2O5VH/5grT760j/t0UpX3vGeHPPKWIxZemRFpsqSNbJncEgFufbnmak9Pr/OeqdkFmAq60qpi9TZzsgukYLvYFg6y4cpNRhcV8eB25nwwGdiUdOgSAr/sVTPQ3B6D+eCDuxglpKL81rmmOl3DfocZkgnPbChhLlfrEw9Rc7Z2nMh2AXJH7baRSfzyFoj+ynfc7GjJeqnrPKXrasmR6XAvT+IPiKMMioUtBzfRCHV+yfgQ7WPAqEcuZWKzgeWXtCGb4kPgP9RumVcoMbzh1hjakSX2eceLfsYvs+ES5lhW6BY15KqdA8Kzdrzsja1BnLi8ljukadazm0SKKLk96fAyW7vggwbDYQtIPGXJZVIfmMc8fjXprCPxLupkyYRzlBUxOgJ/IhzkN1i01jxePSVAd2nF301stDbsiPSszTKoOn8QbT0rdkUsnKDU/BdzF5dkQ3FLzXYy4lDdseeMj8+Dmp058kudk6xLNygCkI="
#             FTP_USER_1
    - secure: "ooMM0x9v8IBWXCGA6kIfESGI0jpv5FeT3RFxrqNS8pbjJssTj4hTIkWt6yDeuO0OML7SrYvBLwsDwwy0+AKeSJFBNEr5fsuGm9QAUAgD6P3fn49dSUT/essAGMRl5SwIx+6boL0Z27q2ueeL815bWQZpZxec23LA6pR5mZ/lNATxfM8X4vBQg8UV2yhBdwpvfcCivRUw1wSHYHyQyMNJSest0NN/Zs76oCmtURPH3MAqp6h8MdHPzPpH9bpV9NQHJCooKnaYoLe5GfouBemGBV939lwNe9uChVBHjIAnHmtxGEnkC9lVbxjIGa7Or+R/Hpmr8s9LCfCa9o2Psj7SIp7yBUcEPLHP8KN2YUeHzssuHKDp860dFbR2z9kwoPgPWtPrd8l8NbGjtXSjbcaMw5au/AVHfwExKNnFMMBdmFzKc8oMx85d7a0UAaI75scPYGLUboYpOHLxe9ACDryKAfkISrblKHbJY+L6CvSyj9hzB0ntJEe/80Vy9HTOz7KBM4x1sV1m2/7YgpByYgGke9EzcoLiqtlKQvRpQq3tVhSNnjCpQKpJSg1m8lV/FqOpRd9vPNyLYg4TuwIlRymu0qWGXacte6nzxW7tK10peBBfIaChOvE+SU1AWIX745XntKmuW3m6kS98cIJWtGoMaPMKNfQHOzsLUxPtH1TXFok="
#             FTP_PASSWORD
    - secure: "Jv9jf7xqsymzopfKsu5yoAkbJbHlE8X6FkDebVjBUXjQ33jfgKHEHLRe+MuV+7ZTcUMBdpkwmaPq1+PC3ikehuOHBGTNv8WAVBSibX8qxr1ItrnreZP3bxxTlhMGj7t6GcaFEqOsK1tJtw43UG3lnDMSceavN7aAiQ1xKQeDhg9reiGNnrDINFcJ03Uw17Xf8BRhGVW9tFElNmxZqQDVG7YuoszczvrM4ieDRtxr1AcK3x3HRU+9R9/pbUQLxwbvUDUFK4t1ozuWDqd6Gf4HdPMCZsnJh5DgYXt4JkD2OuOAOGwUnZoL/XOZlohW5aN6Y00ABBI2+LNPvZHK637K5mE/BTm7WXSioqFkNSKwJDXh2rwPzGAzAqrTvoyv0/Z7pL4veS6m8sWpAr7Q3Zy4mr3Xx/JNHCImSFNBNkP0K7RMRkFNrnZkF8P+C9+/P8fEjpn2pwGRfU/E4tLArEj6SKRceZKTjOBAb2Ij5izWwzQiZsG13l3UH9+5iLtbLuO6h/TArQBpKcwp1Nk6UJoQl/xgCKGk45nRHHEYykR4mHxI9EQqe20B9o2VxhRxfjtq7L/91Ax3EbFvEK5jKwUwZOzjH7XR5YYNfVP/ny1Xdc/k5EKjvxqzebHGF4yiSUxpG5pRa9wPTDb4cgLVPdvoRPwxMNCCLHJyHYD07eoFk7k="


notifications:
  slack:
    rooms:
      - secure: Rxjp4bNLl/kx9dbQxpXtHi2KEl7M25/gJcG874IlF40B9tnPwRmGm+w8m3smQW7gRNLyZ6VfoBcmuGet+GMBTCCa44dCcm9qkx+OZJkOBv/C5TLEO4dBtAMFDhRRmpr2LhZfxvbC0R0CRP3wzGIea4RWFJBcvF/oAtGxYSfISpEE745DDY/W9yNRk3AchFDvb9T3f6ip3JDJnamdBh5xMUD1Ou6HiTUjXm4qrwwG89Lf9MrzmN3LOuP/+wE/w+wz4MeEYuPWMfQIYGdI0Bhz7zglmRpBPX4F6FSN9LyBrTORZz09erXLwcz7kyP+LfA3cXrvoMSD4eR8mSyRxV20o7p5+phHNdYkpohmoOwOPO7cT/yfSSjQIzCN4NYeIxTTXed4AyAfDFCVrB8o5sqs2QC1O7MuNOgKw1DDvUMNRLd+8x41xpdr0dZC1OxgJ0glURaHq1e7C2GqjzKgd0wm1bYhnOWWLMwe4S9mrxo8/bKG6JQ0TchXkr5PHo02QT+HTiDysDgsa+etyM4zIMbNpp3aYQsNMxu3IOgzINUgcnoVreyXlht1QGEu8I6WIWNWYnBmdjx+aK7V2dKeEx5LLqJ/RO5+CWaXyYIdg7EYQn/WIx9Z5ifCs4s8m7ZqKYd6D+1KpfrrhMtnZ/uTJ/HVHkLwyW7DX/caRn7kpnQU5Xc=
    template:
      - "NFsim build: %{result} in %{duration}"
      - "Build: <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) Author: %{author}"   
      - "To download the NFsim executable, "
      - "Goto: https://rawgit.com/RuleWorld/nfsim/master/.NFsim_Beta.html"
      - "To package NFsim, please make a small modification to BioNetGen:"
      - "Goto: https://github.com/RuleWorld/bionetgen"
      - "Build details:  %{build_url} "


before_install:
- source osx_install.sh

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script: 
  - mkdir -p build; mkdir -p dist; cd build; cmake ..; make; cp NFsim ../dist; cp NFsim ../dist/NFsim-$TRAVIS_OS_NAME ;cd ..; 
  - cd validate;tar xfj bionetgen-2.2.6.tar.bz2
  - python validate.py
  - cd ..
  
after_success:
#  - perl .make_tar.pl  --platform $TRAVIS_OS_NAME
  - source .curl_ftp.sh
