environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  matrix:
    - generator: "Ninja"

install:
  - choco install -y mingw
  - choco install -y ninja
  - "SET PATH=C:\\tools\\mingw64\\bin;%PATH%"
  - cmd: echo Running cmake ...
  - mkdir build
  - cd build
  - cmake -G "Ninja" ..
  - ninja

branches:
  # whitelist
  only:
    - master
    - release
    - mcell
    - release-windows




build:
