version: 1.12
environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  matrix:
    - generator: "MinGW Makefiles"

install:
  - choco install -y mingw
  - "SET PATH=C:\\tools\\mingw64\\bin;%PATH%"
  - cmd: echo Running cmake ...
  - mkdir build
  - cmd: cd build
  - cmd: cmake ..
  - cmd: make

branches:
  # whitelist
  only:
    - master
    - release
    - mcell
    - release-windows




build:
